---
title: "TDA Package Intro"
output: html_notebook
---

```{r packages}
library(magrittr)
library(tidyverse)
library(TDA)
library(tidytext)
library(ggplot2)
```


```{r import_data}
data("stop_words")
df_original <- read_csv("D:/southparklines/All-seasons.csv")
```


```{r}
df <- df_original %>%
  mutate(LineNumber = row_number()) %>%
  unnest_tokens(word, Line) %>%
  anti_join(stop_words)

```



```{r}
df %>%
  count(word) %>%
  arrange(desc(n)) %>%
  filter(n > 900) %>%
  ggplot(aes(reorder(word,n), n)) +
  geom_col() + 
  coord_flip() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("South Park Seasons 1 to 18 Most Frequent Words",
          "Filtered by words used greater than 900 times")
```

```{r}
idfset_season 
  
df %>%
  count(Season, word, sort = TRUE) %>%
  ungroup() %>%
  bind_tf_idf(word, Season, n) %>%
  arrange(desc(tf_idf)) %>%
  head(25) %>%
  ggplot(aes(reorder(word, tf_idf), tf_idf)) +
  geom_col() +
  coord_flip() +
  xlab(NULL) + 
  ggtitle("Important Words by Season")


```


























