---
title: "Mapping Jowett"
author: "Fred Kaesmann"
date: "6/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r packs}
##### Packages ####
library(readr)
library(tidyverse)
library(tidyr)
library(stopwords)
library(gutenbergr) 
library(stringr)
library(FredsVietorisRips)
```


```{r import_data}
##### The Works of Plato ####

df_original <- read_csv("D:/plato.csv")

# Uncomment the below to dowload the raw from gutenberg.org
# books <- gutenberg_works(gutenberg_author_id == 93) %>%
#   gutenberg_download(meta_fields = "title") %>%
#   filter(gutenberg_id < 1751)
# 
# df <- books %>%
#   mutate(linenumber = row_number()) %>%
#   group_by(title) %>%
#   unnest_tokens(word, text) %>%
#   anti_join(stop_words) %>%
#   summarise(text = str_c(word, collapse = " ")) 

df <- df_original %>%
  group_by(title) %>%
  unnest_tokens(text, text) %>%
  summarise(text = str_c(text, collapse = " "))

```

There is a lot of introductory text and analysis by Jowett himself. 
We have opted to keep it in and consider it as added content.

How to proceed:
\begin{enumerate}
  \item Map similarity of each work to the other
  
  \item Figure out if there is a better way to cluster the text if chapter 
  headings aren't provided 
  
  \item 
\end{enumerate}


```{r text2vec}

##### Tokenize Sample ####
it_sample <- df$text %>%
  itoken(progressbar = FALSE)

##### Vectorize (?) ####
vectorizer <- df$text %>%
  itoken(progressbar = FALSE) %>%
  create_vocabulary() %>%
  prune_vocabulary() %>% 
  vocab_vectorizer()

##### Document Term Matrix ####
dtm_sample <- create_dtm(it_sample, vectorizer)
# dim(dtm_sample)

##### Jaccard Similarity ####
jacsim <- sim2(dtm_sample, dtm_sample, method = "jaccard", norm = "none")
# dim(jacsim)

##### Convert fancy object to matrix ####
jsmat <- jacsim %>%
  as.matrix() 

# Flip it around so 1 is max distance 
# and 0 indicates two sets are the same
jsmat <- 1 - jsmat 

```


```{r}
for (ep in c(.75, .775, .8, .825, .85, .875)) {
  ##### Plot Adjacencies ####
  jsmat %>%
    AdjacencyMatrix(ep) %>%
    graph_from_adjacency_matrix(mode = "undirected") %>%
    plot(main=paste("Epsilon =", ep))
}
```

```{r evaluate_clusters, include=F, echo=F}
epsilon <- 0.75
clusters


adjmat <- jsmat %>%
  AdjacencyMatrix(epsilon) 



  get_cluster(adjmat, minimum_connections = 1, c(1:25))
  
sum(adjmat[11, ])
  
  FredsDBSCAN(adjmat, minimum_connections = 2, c(1:nrow(jsmat)))
```






